-- ====================================================================
-- STEP 1: SETUP DATABASE, SCHEMAS, AND METADATA TABLES
-- Run this file first! It builds the foundation.
-- ====================================================================

-- 1. Create the Database and Schemas
CREATE DATABASE IF NOT EXISTS CUSTOMER_PIPELINE_DB;
CREATE SCHEMA IF NOT EXISTS CUSTOMER_PIPELINE_DB.RAW;
CREATE SCHEMA IF NOT EXISTS CUSTOMER_PIPELINE_DB.ETL;

-- 2. Create the ETL Execution Log Table
CREATE TABLE IF NOT EXISTS CUSTOMER_PIPELINE_DB.ETL.ETL_LOG (
    LOG_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1,
    CONFIG_ID NUMBER(38,0),
    SOURCE_PATH VARCHAR(16777216),
    GD_PATH VARCHAR(16777216),
    SOURCE_FILE_NAME VARCHAR(16777216),
    FILE_STATUS VARCHAR(16777216),
    FILE_FORMAT VARCHAR(16777216),
    IMPORT_STARTTS TIMESTAMP_NTZ(9),
    IMPORT_COMPLETETS TIMESTAMP_NTZ(9),
    SOURCE_ROWCOUNT NUMBER(38,0),
    TABLE_NAME VARCHAR(16777216),
    TABLE_LOAD_STATUS VARCHAR(16777216),
    INSERTION_ROWCOUNT NUMBER(38,0),
    TABLE_LOAD_MESSAGE VARCHAR(16777216),
    TABLE_LOADTS TIMESTAMP_NTZ(9),
    CREATED_AT TIMESTAMP_NTZ(9),
    RUNID VARCHAR(16777216),
    DATADATE DATE
);

-- 3. Create the Pipeline Configuration Table
CREATE OR REPLACE TABLE CUSTOMER_PIPELINE_DB.ETL.SOURCE_CONFIG (
    CONFIG_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    VENDOR VARCHAR(100),
    EXTRACT_LOCATION VARCHAR(1000),
    GD_LOCATION VARCHAR(1000),
    SCHEMA_NAME VARCHAR(100),
    TABLE_NAME VARCHAR(100),
    FILE_NAME_PATTERN VARCHAR(255),
    FILE_FORMAT VARCHAR(50),
    DATA_DELIMITER VARCHAR(10),
    COLUMN_LIST VARCHAR(2000),
    NULLABLE_COLUMNS VARCHAR(2000) DEFAULT '',
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR(100) DEFAULT CURRENT_USER()
);

-- 4. Apply Security Grants for Airflow
-- Ensures the Airflow service account can read configurations and insert data.
GRANT USAGE ON DATABASE CUSTOMER_PIPELINE_DB TO ROLE AIRFLOW_LOADER_ROLE;
GRANT USAGE ON SCHEMA CUSTOMER_PIPELINE_DB.RAW TO ROLE AIRFLOW_LOADER_ROLE;
GRANT USAGE ON SCHEMA CUSTOMER_PIPELINE_DB.ETL TO ROLE AIRFLOW_LOADER_ROLE;
GRANT SELECT, INSERT ON TABLE CUSTOMER_PIPELINE_DB.ETL.ETL_LOG TO ROLE AIRFLOW_LOADER_ROLE;
GRANT SELECT ON TABLE CUSTOMER_PIPELINE_DB.ETL.SOURCE_CONFIG TO ROLE AIRFLOW_LOADER_ROLE;
