-- ====================================================================
-- STEP 2: SETUP ALL RAW DATA TABLES
-- Run this AFTER 01_setup_database.sql
-- ====================================================================
-- 1. Creates all 10 RAW data tables (wipes existing data with OR REPLACE)
-- 2. Grants Airflow required permissions on all 10 tables
-- ====================================================================

-- -----------------------------------------------------------------------
-- 1. Create the 10 RAW data tables
-- -----------------------------------------------------------------------

-- CONFIG 1: CUSTOMER
CREATE OR REPLACE TABLE CUSTOMER_PIPELINE_DB.RAW.CUSTOMER (
    CUSTOMER_ID   VARCHAR(50),
    NAME          VARCHAR(255),
    CITY          VARCHAR(100),
    COUNTRY       VARCHAR(100),
    SIGNUP_DATE   DATE,
    EMAIL         VARCHAR(255),
    PHONE         VARCHAR(50),
    AGE           NUMBER,
    LOADED_AT     TIMESTAMP_NTZ(9),
    SOURCE_RUN_ID VARCHAR(255)
);

-- CONFIG 2: ORDERS
CREATE OR REPLACE TABLE CUSTOMER_PIPELINE_DB.RAW.ORDERS (
    ORDER_ID      VARCHAR(50),
    CUSTOMER_ID   VARCHAR(50),
    ORDER_DATE    DATE,
    STATUS        VARCHAR(50),
    TOTAL_AMOUNT  NUMBER(12,2),
    PRODUCT_NAME  VARCHAR(255),
    CATEGORY      VARCHAR(100),
    QUANTITY      NUMBER,
    DISCOUNT      NUMBER(12,2),
    LOADED_AT     TIMESTAMP_NTZ(9),
    SOURCE_RUN_ID VARCHAR(255)
);

-- CONFIG 3: ORDER_ITEMS
CREATE OR REPLACE TABLE CUSTOMER_PIPELINE_DB.RAW.ORDER_ITEMS (
    ORDER_ITEM_ID VARCHAR(50),
    ORDER_ID      VARCHAR(50),
    PRODUCT_ID    VARCHAR(50),
    QUANTITY      NUMBER,
    UNIT_PRICE    NUMBER(12,2),
    LOADED_AT     TIMESTAMP_NTZ(9),
    SOURCE_RUN_ID VARCHAR(255)
);

-- CONFIG 4: PAYMENTS
CREATE OR REPLACE TABLE CUSTOMER_PIPELINE_DB.RAW.PAYMENTS (
    PAYMENT_ID      VARCHAR(50),
    ORDER_ID        VARCHAR(50),
    PAYMENT_METHOD  VARCHAR(50),
    PAYMENT_DATE    DATE,
    AMOUNT          NUMBER(12,2),
    PAYMENT_STATUS  VARCHAR(50),
    LOADED_AT       TIMESTAMP_NTZ(9),
    SOURCE_RUN_ID   VARCHAR(255)
);

-- CONFIG 5: PRODUCTS
CREATE OR REPLACE TABLE CUSTOMER_PIPELINE_DB.RAW.PRODUCTS (
    PRODUCT_ID     VARCHAR(50),
    PRODUCT_NAME   VARCHAR(255),
    CATEGORY       VARCHAR(100),
    BRAND          VARCHAR(100),
    PRICE          NUMBER(12,2),
    STOCK_QUANTITY NUMBER,
    SUPPLIER       VARCHAR(255),
    LOADED_AT      TIMESTAMP_NTZ(9),
    SOURCE_RUN_ID  VARCHAR(255)
);

-- CONFIG 6: EMPLOYEES
CREATE OR REPLACE TABLE CUSTOMER_PIPELINE_DB.RAW.EMPLOYEES (
    EMPLOYEE_ID   VARCHAR(50),
    NAME          VARCHAR(255),
    DEPARTMENT    VARCHAR(100),
    HIRE_DATE     DATE,
    EMAIL         VARCHAR(255),
    MANAGER_ID    VARCHAR(50),
    SALARY        NUMBER(12,2),
    LOADED_AT     TIMESTAMP_NTZ(9),
    SOURCE_RUN_ID VARCHAR(255)
);

-- CONFIG 7: RETURNS
CREATE OR REPLACE TABLE CUSTOMER_PIPELINE_DB.RAW.RETURNS (
    RETURN_ID     VARCHAR(50),
    ORDER_ID      VARCHAR(50),
    CUSTOMER_ID   VARCHAR(50),
    RETURN_DATE   DATE,
    REASON        VARCHAR(500),
    REFUND_AMOUNT NUMBER(12,2),
    STATUS        VARCHAR(50),
    LOADED_AT     TIMESTAMP_NTZ(9),
    SOURCE_RUN_ID VARCHAR(255)
);

-- CONFIG 8: REVIEWS
CREATE OR REPLACE TABLE CUSTOMER_PIPELINE_DB.RAW.REVIEWS (
    REVIEW_ID     VARCHAR(50),
    ORDER_ID      VARCHAR(50),
    CUSTOMER_ID   VARCHAR(50),
    RATING        NUMBER(3,1),
    REVIEW_TEXT   VARCHAR(2000),
    REVIEW_DATE   DATE,
    LOADED_AT     TIMESTAMP_NTZ(9),
    SOURCE_RUN_ID VARCHAR(255)
);

-- CONFIG 9: SHIPMENTS
CREATE OR REPLACE TABLE CUSTOMER_PIPELINE_DB.RAW.SHIPMENTS (
    SHIPMENT_ID     VARCHAR(50),
    ORDER_ID        VARCHAR(50),
    CARRIER         VARCHAR(100),
    SHIP_DATE       DATE,
    DELIVERY_DATE   DATE,
    TRACKING_NUMBER VARCHAR(100),
    SHIPPING_COST   NUMBER(10,2),
    LOADED_AT       TIMESTAMP_NTZ(9),
    SOURCE_RUN_ID   VARCHAR(255)
);

-- CONFIG 10: SUPPLIERS
CREATE OR REPLACE TABLE CUSTOMER_PIPELINE_DB.RAW.SUPPLIERS (
    SUPPLIER_ID   VARCHAR(50),
    SUPPLIER_NAME VARCHAR(255),
    CITY          VARCHAR(100),
    COUNTRY       VARCHAR(100),
    CONTACT_EMAIL VARCHAR(255),
    CONTACT_PHONE VARCHAR(50),
    LOADED_AT     TIMESTAMP_NTZ(9),
    SOURCE_RUN_ID VARCHAR(255)
);


-- -----------------------------------------------------------------------
-- 2. Grant permissions on the 10 tables
-- -----------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE CUSTOMER_PIPELINE_DB.RAW.CUSTOMER    TO ROLE AIRFLOW_LOADER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE CUSTOMER_PIPELINE_DB.RAW.ORDERS      TO ROLE AIRFLOW_LOADER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE CUSTOMER_PIPELINE_DB.RAW.ORDER_ITEMS TO ROLE AIRFLOW_LOADER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE CUSTOMER_PIPELINE_DB.RAW.PAYMENTS    TO ROLE AIRFLOW_LOADER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE CUSTOMER_PIPELINE_DB.RAW.PRODUCTS    TO ROLE AIRFLOW_LOADER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE CUSTOMER_PIPELINE_DB.RAW.EMPLOYEES   TO ROLE AIRFLOW_LOADER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE CUSTOMER_PIPELINE_DB.RAW.RETURNS     TO ROLE AIRFLOW_LOADER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE CUSTOMER_PIPELINE_DB.RAW.REVIEWS     TO ROLE AIRFLOW_LOADER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE CUSTOMER_PIPELINE_DB.RAW.SHIPMENTS   TO ROLE AIRFLOW_LOADER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE CUSTOMER_PIPELINE_DB.RAW.SUPPLIERS   TO ROLE AIRFLOW_LOADER_ROLE;
